pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 99d
    - name: git
      image: alpine/git
      command:
        - sleep
      args:
        - 99d
"""
    }
  }

  environment {
    AWS_ACCOUNT_ID = "${env.AWS_ACCOUNT_ID ?: '451664151890'}"
    AWS_REGION     = "${env.AWS_REGION ?: 'eu-north-1'}"
    ECR_REGISTRY   = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    IMAGE_NAME     = "app-repo"
    IMAGE_TAG      = "v1.0.${BUILD_NUMBER}"

    COMMIT_EMAIL   = "jenkins@localhost"
    COMMIT_NAME    = "jenkins"
    GIT_REPO_URL   = "github.com/ma-nk/goit-devops-course.git"
    TARGET_BRANCH  = "final_project"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
        script {
          def msg = sh(returnStdout: true, script: 'git log -1 --pretty=%B').trim()
          env.SKIP_CI = msg.contains('[skip ci]') ? 'true' : 'false'
        }
      }
    }

    stage('ECR Login') {
      steps {
        container('git') {
          sh 'echo "ECR Login authentication handled via AWS EKS IRSA Role."'
        }
      }
    }

    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor \
              --context="dir://${WORKSPACE}" \
              --dockerfile="${WORKSPACE}/lesson-7/Dockerfile" \
              --destination=$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
              --cache=true
          '''
        }
      }
    }

    stage('Update Chart Tag in Git') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PAT')]) {
            sh '''
              git clone https://$GIT_USERNAME:$GIT_PAT@$GIT_REPO_URL repo
              cd repo
              git checkout $TARGET_BRANCH || git checkout -b $TARGET_BRANCH

              sed -i "s|tag: .*|tag: $IMAGE_TAG|" lesson-7/charts/django-app/values.yaml

              git config user.email "$COMMIT_EMAIL"
              git config user.name "$COMMIT_NAME"

              git add lesson-7/charts/django-app/values.yaml
              git commit -m "Update image tag to $IMAGE_TAG [skip ci]"
              git push origin $TARGET_BRANCH
            '''
          }
        }
      }
    }
  }

  post {
    success {
      script {
        if (env.SKIP_CI == 'true') {
          echo "No app changes to build (skip ci commit)."
        } else {
          echo "Pipeline OK. Image ${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} pushed."
        }
      }
    }
    failure {
      echo "Pipeline failed. Check the stage logs above."
    }
    always {
      cleanWs()
    }
  }
}
