applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/ma-nk/goit-devops-course.git
      path: lesson-7/charts/django-app
      targetRevision: lesson-8-9
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories: []

repoConfig:
  insecure: "true"
  enableLfs: "true"


