image:
  repository: 451664151890.dkr.ecr.eu-north-1.amazonaws.com/app-repo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

config:
  POSTGRES_DB: myapp
  POSTGRES_USER: postgres
  POSTGRES_HOST: myapp-db
  POSTGRES_PORT: "5432"
  DATABASE_HOST: myapp-db
  DATABASE_PORT: "5432"
  DEBUG: "True"
  ALLOWED_HOSTS: "*"

secrets:
  POSTGRES_PASSWORD: ChangeMe123Secret!
  DJANGO_SECRET_KEY: django-insecure-secret-key-12345


resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
